### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by KwiatekMiki** [FlyTechVideos/evil-clippy#1]
https://github.com/FlyTechVideos/evil-clippy/assets/79092746/0b160eb5-7a1f-497b-be29-e9e2f3e0c193

**Comment by FlyTechVideos** [comment]
Can you try pressing Control + , ?

**Comment by KwiatekMiki** [comment]
It's not doing anything.

**Comment by KwiatekMiki** [comment]
I also noticed that background processes spawn after opening but it still won't react.

https://github.com/FlyTechVideos/evil-clippy/assets/79092746/e4e03735-df44-40cc-9dd6-9ed3510799b2

---

Another test and it didn't even spawn a background process but this time I only opened it once.

https://github.com/FlyTechVideos/evil-clippy/assets/79092746/adac71fa-ac07-47f2-b73f-26ff2708ece5

After opening it again on the same machine it spawned a background process but there was no reaction.

**Comment by FlyTechVideos** [comment]
Okay, this is weird, and I have never encountered this on any machine I tested with. Can you check event logs?

**Comment by KwiatekMiki** [comment]
![V7bXKywVtR](https://github.com/FlyTechVideos/evil-clippy/assets/79092746/83a8b808-4343-48c8-ad4b-8a49b3d13c40)
This would appear every time I open this application

**Comment by blackneeed** [comment]
Maybe WDAC?

**Comment by FlyTechVideos** [comment]
@KwiatekMiki Sounds like a problem on your machine. Maybe this helps https://stackoverflow.com/q/64669672/3673616

**Comment by KwiatekMiki** [comment]
~~will try tomorrow.~~

**Comment by eclipse1408** [comment]
Can confirm on Windows 10 22H2.

**Comment by KwiatekMiki** [comment]
closing because i dont have time to test this
